require:
  - 'rubocop-performance'
  - 'rubocop-rails'
  - 'rubocop-rspec'

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/rails_helper.rb'
    - 'Rakefile'
  TargetRailsVersion: 7.0
  TargetRubyVersion: 3.1.0

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Max: 20

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'conxtet']
